In [1]:
# importing data from excel to python
import numpy as np
import pandas as pd
vector_space = pd.read_excel("LabSession1.xlsx", sheet_name = "Sheet2", index_col=0)
vector_space


Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)
Customer                                                           
C_1                20             6                 2           386
C_2                16             3                 6           289
C_3                27             6                 2           393
C_4                19             1                 2           110
C_5                24             4                 2           280
C_6                22             1                 5           167
C_7                15             4                 2           271
C_8                18             4                 2           274
C_9                21             1                 4           148
C_10               16             2                 4           198

In [2]:
#finding row by column
dimensions = vector_space.shape
print(dimensions)

(10, 4)


In [3]:
A = np.array([[20,6,2],[16,3,6],[27,6,2],[19,1,2],[24,4,2],[22,1,5],[15,4,2],[18,4,2],[21,1,4],[16,2,4]])
A

array([[20,  6,  2],
       [16,  3,  6],
       [27,  6,  2],
       [19,  1,  2],
       [24,  4,  2],
       [22,  1,  5],
       [15,  4,  2],
       [18,  4,  2],
       [21,  1,  4],
       [16,  2,  4]])

In [4]:
X = np.array([['a'],['b'],['c']])
X

array([['a'],
       ['b'],
       ['c']], dtype='<U1')

In [5]:
C = np.array([[386],[289],[393],[110],[280],[167],[271],[274],[148],[198]])
C

array([[386],
       [289],
       [393],
       [110],
       [280],
       [167],
       [271],
       [274],
       [148],
       [198]])

In [6]:
#finding rank of a matrix
rank = np.linalg.matrix_rank(A)

print('Matrix : ', A)
print('Rank of the given Matrix : ',rank)

Matrix :  [[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
Rank of the given Matrix :  3


In [7]:
p = np.linalg.pinv(A) #pseudo inverse formula A+ = (A'A)-1A'
print(p)

[[-0.01008596 -0.03124505  0.01013951  0.0290728   0.0182907   0.01161794
  -0.00771348  0.00095458  0.01743623 -0.00542016]
 [ 0.09059668  0.07263726  0.03172933 -0.09071908 -0.01893196 -0.06926996
   0.05675464  0.03152577 -0.07641966  0.00357352]
 [ 0.00299878  0.15874243 -0.05795468 -0.06609024 -0.06295043  0.03348017
   0.01541831 -0.01070461  0.00029003  0.05938755]]
